Fixed bug where settings a custom urlOpener no longer worked
M2mobi/Marky-Mark pull request #109
Opened 2021-07-05 14:21 UTC by jvanzummeren

2021-07-09 10:29 UTC, houtzager requested changes

2021-07-09 10:29 UTC, houtzager commented on markymark/Classes/Renderer/Configurations/MarkdownToViewConverterConfiguration.swift
You should still set the local urlOpener to the passed urlOpener. Right now urlOpener is unused causing the initial urlOpener never to be set.

2021-07-09 10:29 UTC, houtzager commented on markymark/Classes/Protocols/CanSetURLOpener.swift
> +protocol CanSetURLOpener {
Why did you decide to go for a setter function-based protocol over having a property-based one that allows setting?

2021-07-09 10:29 UTC, houtzager commented on markymark/Classes/Renderer/Configurations/MarkdownToViewConverterConfiguration.swift
> +    func setUrlOpenerIfNeeded(_ layoutBlockBuilder: LayoutBlockBuilder<UIView>) {
setUrlOpenerIfPossible is more applicable IMO.

2021-07-19 13:14 UTC, Tj3n commented
Hi, when will this be merged? The `urlOpener` is not working at all. Thanks.

2021-07-20 06:14 UTC, houtzager commented on markymark/Classes/Protocols/CanSetURLOpener.swift
> +protocol CanSetURLOpener {
Discussed internally, it's decided to go for a setter through a function only because a getter is not needed.

2021-07-20 06:15 UTC, houtzager approved these changes

2021-07-20 06:17 UTC, merged